export const allBrands = {
  addiction: 'ADDICTION',
  albion: 'ALBION',
  bobbibrown: 'BOBBI BROWN',
  clarins: 'CLARINS',
  cledepeaubeaute: 'Cle de Peau Beaute',
  chanel: 'CHANEL',
  decorte: 'DECORTE',
  dior: 'DIOR',
  esteelauder: 'ESTEE LAUDER',
  guerlain: 'GUERLAIN',
  givenchy: 'GIVENCHY',
  ipsa: 'IPSA',
  jillstuart: 'JILL STUART',
  lauramercier: 'laura mercier',
  lancome: 'LANCOME',
  lunasol: 'LUNASOL',
  mac: 'M・A・C',
  nars: 'NARS',
  pauljoe: 'PAUL&JOE',
  rmk: 'RMK',
  shiseido: 'SHISEIDO',
  shuuemura: 'shuuemura',
  suqqu: 'SUQQU',
  three: 'three',
  tomford: 'TOM FORD',
}

export const allTypes = {
  liquid: 'リキッド',
  powder: 'パウダー',
  cream: 'クリーム',
  cushion: 'クッション',
}